name: Deploy to flamecloud_admin

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Deploy to flamecloud_admin
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAT }}
          external_repository: flamecloudcn/php_flamecloud_admin
          publish_dir: ./
          publish_branch: master
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'